# Generated by Django 3.1.4 on 2022-09-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
